# Generated by Django 2.1.3 on 2019-07-06 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InputMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('body', models.CharField(max_length=100)),
                ('channel', models.CharField(max_length=50)),
                ('pub_date', models.DateTimeField()),
            ],
        ),
    ]
