# Generated by Django 2.1.3 on 2019-07-06 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputmessage',
            name='pub_date',
            field=models.DateTimeField(default='2000-09-04 06:00:00.000000'),
        ),
    ]
