# Generated by Django 2.1.3 on 2019-07-01 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inputmessage',
            old_name='name',
            new_name='sender_name',
        ),
    ]
