# Generated by Django 2.1.3 on 2019-07-01 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_auto_20190701_0820'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inputmessage',
            old_name='sender_name',
            new_name='name',
        ),
    ]
