# Generated by Django 2.1.3 on 2021-10-17 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0003_inputmessage_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inputmessage',
            name='channel',
        ),
    ]
