language: python

python:
  - "3.6"

services: postgresql

install:
  - pip install -r requirements.txt

before_script:
  - psql -c "CREATE DATABASE mydb;" -U postgres
  - psql -c "CREATE USER myuser WITH PASSWORD 'password';" -U postgres
  - psql -c "ALTER USER myuser CREATEDB;" -U postgres

script:
  - python manage.py test

addons:
  postgresql: "9.6"
# un-comment to deploy to AWS Elastic Beanstalk through Travis CI
# deploy:
#   provider: elasticbeanstalk
#   access_key_id: $ACCESSKEYID
#   secret_access_key:
#     secure: "$SECRETACCESSKEY"
#   region: "us-west-2"
#   app: "slackify-project"
#   env: "dev-env3"
#   bucket_name: "matlau.slackify"
#   on:
#     branch: master
